sudo: false
language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - hhvm
matrix:
    allow_failures:
        - php: 7.1
before_script:
  - cp tests/config/config.travis-ci.php tests/config/config.php
  - composer install --dev
